language: elixir
sudo: false
cache:
  directories:
    - _build
    - deps
elixir:
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 19.3
  - 20.3
  - 21.2
matrix:
  exclude:
    - elixir: 1.8
      otp_release: 19.3
